### PR TITLE
new function to get and set timeout

### PR DESCRIPTION
**Pull request by edelciomolina**
This makes possible change the default timeout. 1000ms is too fast for the perfect analyse with some internet connections.

### CODE REVIEW

**Comment by skoranga** [comment]
@edelciomolina linting failed. PR looks good, will merge and publish once CI is green

**Comment by edelciomolina** [comment]
@skoranga, new commit with fix to lint.
https://github.com/skoranga/node-connection-tester/commit/c30df3ce448db09e783fc2dc88f52a2c10d7f7a6

**Comment by skoranga** [comment]
👍

**Comment by skoranga** [comment]
published `connection-tester@0.1.2`

**Pull request merged**
